### ISSUE TITLE
爬取不到内容

### ISSUE THREAD

**Issue by Dinosaurcubs** [NanmiCoder/MediaCrawler#100]
(bling) PS E:\git code\MediaCrawler-main> python .\main.py
2023-12-17  21:27:10 MediaCrawler INFO Begin create browser context ... 
2023-12-17  21:27:12 MediaCrawler INFO Begin create xiaohongshu API client ... 
2023-12-17  21:27:12 MediaCrawler INFO Begin to pong xhs...
2023-12-17  21:27:13 MediaCrawler INFO Begin login xiaohongshu ... 
2023-12-17  21:27:13 MediaCrawler INFO Begin login xiaohongshu by qrcode ...
2023-12-17  21:27:35 MediaCrawler INFO waiting for scan code login, remaining time is 120s 
2023-12-17  21:27:47 MediaCrawler INFO Login successful then wait for 5 seconds redirect ... 
2023-12-17  21:27:52 MediaCrawler INFO Begin search xiaohongshu keywords 
2023-12-17  21:27:52 MediaCrawler INFO Current search keyword: 伊姆斯躺椅
2023-12-17  21:27:52 MediaCrawler INFO Note details: [] 
2023-12-17  21:27:52 MediaCrawler INFO Begin batch get note comments, note list: []
2023-12-17  21:27:52 MediaCrawler INFO Note details: [] 
2023-12-17  21:27:52 MediaCrawler INFO Begin batch get note comments, note list: []
2023-12-17  21:27:52 MediaCrawler INFO Note details: [] 
2023-12-17  21:27:52 MediaCrawler INFO Begin batch get note comments, note list: []
2023-12-17  21:27:53 MediaCrawler INFO Note details: [] 
2023-12-17  21:27:53 MediaCrawler INFO Begin batch get note comments, note list: []
2023-12-17  21:27:53 MediaCrawler INFO Note details: [] 
2023-12-17  21:27:53 MediaCrawler INFO Begin batch get note comments, note list: []
2023-12-17  21:27:53 MediaCrawler INFO Note details: [] 
2023-12-17  21:27:53 MediaCrawler INFO Begin batch get note comments, note list: []
2023-12-17  21:27:53 MediaCrawler INFO Note details: [] 
2023-12-17  21:27:53 MediaCrawler INFO Begin batch get note comments, note list: []
2023-12-17  21:27:54 MediaCrawler INFO Note details: [] 
2023-12-17  21:27:54 MediaCrawler INFO Begin batch get note comments, note list: []
2023-12-17  21:27:54 MediaCrawler INFO Note details: [] 
2023-12-17  21:27:54 MediaCrawler INFO Begin batch get note comments, note list: []
2023-12-17  21:27:54 MediaCrawler INFO Note details: [] 
2023-12-17  21:27:54 MediaCrawler INFO Begin batch get note comments, note list: []
2023-12-17  21:27:54 MediaCrawler INFO Xhs Crawler finished ...

一开始能正常爬到内容。试了几次后开始出现登录后控制台也显示扫描QRCODE登录，尝试退出小红书网页登陆或者删除本地user_data后再次扫码进入，出现上述打印信息，不报错但爬取不到内容然后很快结束

**Comment by Dinosaurcubs** [comment]
async def request(self, method, url, **kwargs) -> Dict:
        async with httpx.AsyncClient(proxies=self.proxies) as client:
            response = await client.request(
                method, url, timeout=self.timeout,
                **kwargs
            )
        data: Dict = response.json()
        if data["success"]:
            return data.get("data", data.get("success", {}))
        elif data["code"] == self.IP_ERROR_CODE:
            raise IPBlockError(self.IP_ERROR_STR)
        else:
            raise DataFetchError(data.get("msg", None))


此处获取data字典为：
data
{'code': 0, 'success': True, 'data': {}}
special variables
function variables
'code':
0
'success':
True
'data':
{}
len():
3

**Comment by NanmiCoder** [comment]
这个错误应该是账号被限制了，最新代码我增加了这部分的日志信息，你拉下最新代码看下

**Comment by Dinosaurcubs** [comment]
应该是，刚才爬了几下可以爬取，但配置文件里的参数我改了几个数量啥的就又开始报错了，现在好像是又爬不了了。
帖子数量跟最大评论数能随意换吗？

**Comment by Dinosaurcubs** [comment]
--- Logging error ---
Traceback (most recent call last):
  File "D:\Anaconda\envs\xhs\lib\logging\__init__.py", line 1081, in emit
    msg = self.format(record)
  File "D:\Anaconda\envs\xhs\lib\logging\__init__.py", line 925, in format
    return fmt.format(record)
  File "D:\Anaconda\envs\xhs\lib\logging\__init__.py", line 664, in format
    record.message = record.getMessage()
  File "D:\Anaconda\envs\xhs\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "e:/git code/cloc/MediaCrawler-main/main.py", line 58, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "D:\Anaconda\envs\xhs\lib\asyncio\base_events.py", line 595, in run_until_complete
    self.run_forever()
  File "D:\Anaconda\envs\xhs\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "D:\Anaconda\envs\xhs\lib\asyncio\base_events.py", line 563, in run_forever
    self._run_once()
  File "D:\Anaconda\envs\xhs\lib\asyncio\base_events.py", line 1844, in _run_once
    handle._run()
  File "D:\Anaconda\envs\xhs\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "e:/git code/cloc/MediaCrawler-main/main.py", line 52, in main
    await crawler.start()
  File "e:\git code\cloc\MediaCrawler-main\media_platform\xhs\core.py", line 83, in start
    await self.search()
  File "e:\git code\cloc\MediaCrawler-main\media_platform\xhs\core.py", line 105, in search
    utils.logger.info("Search notes res:", notes_res)
Message: 'Search notes res:'
Arguments: ({},)

**Comment by NanmiCoder** [comment]
sry,最新的错误是我上一次修改导致的，麻烦你重新拉下代码再测试一下，看看有没有问题
