### ISSUE TITLE
报错 ValueError: Set of coroutines/Futures is empty.

### ISSUE THREAD

**Issue by 50chen** [NanmiCoder/MediaCrawler#102]
2023-12-22  14:35:34 MediaCrawler INFO [ProxyIpPool.is_valid_proxy] testing xxx is it valid  
2023-12-22  14:35:38 MediaCrawler INFO Begin search douyin keywords 
2023-12-22  14:35:38 MediaCrawler INFO Current keyword: 顺德村改
2023-12-22  14:35:38 MediaCrawler INFO Current keyword: 顺德村改
2023-12-22  14:35:41 MediaCrawler INFO keyword:顺德村改, aweme_list:[]
Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\MediaCrawler2\main.py", line 58, in <module>       
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\xxx\Desktop\MediaCrawler2\main.py", line 52, in main
    await crawler.start()
  File "C:\Users\xxx\Desktop\MediaCrawler2\media_platform\douyin\core.py", line 73, in start
    await self.search()
  File "C:\Users\xxx\Desktop\MediaCrawler2\media_platform\douyin\core.py", line 104, in search
    await self.batch_get_note_comments(aweme_list)
  File "C:\Users\xxx\Desktop\MediaCrawler2\media_platform\douyin\core.py", line 137, in batch_get_note_comments
    await asyncio.wait(task_list)
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 392, in wait
    raise ValueError('Set of coroutines/Futures is empty.')
ValueError: Set of coroutines/Futures is empty.

请问怎么解决？

**Comment by NanmiCoder** [comment]
首先关闭下 IP 代理试试，如果关闭代理 IP 还是不可用，不要用 `Anaconda` 环境跑这个项目，直接使用 `python3 -m venv venv `创建一个虚拟环境安装依赖试试

**Comment by 50chen** [comment]
感谢答复。换了账号测试，发现是账号爬取达到每日一定量后被限制了。非anaconda环境未测试。
