### ISSUE TITLE
httpx.InvalidURL: Invalid port

### ISSUE THREAD

**Issue by kevinWangSheng** [NanmiCoder/MediaCrawler#133]
报错日志：(myvenv) D:\dev\project\graduationProject\craw\new\MediaCrawler>python main.py --platform dy --lt qrcode --type search
2024-02-08  17:29:50 MediaCrawler INFO [DouYinCrawler.search] Begin search douyin keywords
2024-02-08  17:29:50 MediaCrawler INFO [DouYinCrawler.search] Current keyword: python
Traceback (most recent call last):
  File "D:\dev\project\graduationProject\craw\new\MediaCrawler\myvenv\lib\site-packages\httpx\_urlparse.py", line 339, in normalize_port
    port_as_int = int(port)
ValueError: invalid literal for int() with base 10: 'port'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\dev\project\graduationProject\craw\new\MediaCrawler\main.py", line 59, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "D:\dev\python\python3.9\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\dev\project\graduationProject\craw\new\MediaCrawler\main.py", line 53, in main
    await crawler.start()
  File "D:\dev\project\graduationProject\craw\new\MediaCrawler\media_platform\douyin\core.py", line 74, in start
    await self.search()
  File "D:\dev\project\graduationProject\craw\new\MediaCrawler\media_platform\douyin\core.py", line 90, in search
    posts_res = await self.dy_client.search_info_by_keyword(keyword=keyword,
  File "D:\dev\project\graduationProject\craw\new\MediaCrawler\media_platform\douyin\client.py", line 130, in search_info_by_keyword
    return await self.get("/aweme/v1/web/general/search/single/", params, headers=headers)
  File "D:\dev\project\graduationProject\craw\new\MediaCrawler\media_platform\douyin\client.py", line 81, in get
    return await self.request(method="GET", url=f"{self._host}{uri}", params=params, headers=headers)
  File "D:\dev\project\graduationProject\craw\new\MediaCrawler\media_platform\douyin\client.py", line 68, in request
    async with httpx.AsyncClient(proxies=self.proxies) as client:
  File "D:\dev\project\graduationProject\craw\new\MediaCrawler\myvenv\lib\site-packages\httpx\_client.py", line 1395, in __init__
    proxy_map = self._get_proxy_map(proxies, allow_env_proxies)
  File "D:\dev\project\graduationProject\craw\new\MediaCrawler\myvenv\lib\site-packages\httpx\_client.py", line 216, in _get_proxy_map
    return {
  File "D:\dev\project\graduationProject\craw\new\MediaCrawler\myvenv\lib\site-packages\httpx\_client.py", line 217, in <dictcomp>
    key: None if url is None else Proxy(url=url)
  File "D:\dev\project\graduationProject\craw\new\MediaCrawler\myvenv\lib\site-packages\httpx\_config.py", line 332, in __init__
    url = URL(url)
  File "D:\dev\project\graduationProject\craw\new\MediaCrawler\myvenv\lib\site-packages\httpx\_urls.py", line 113, in __init__
    self._uri_reference = urlparse(url, **kwargs)
  File "D:\dev\project\graduationProject\craw\new\MediaCrawler\myvenv\lib\site-packages\httpx\_urlparse.py", line 246, in urlparse
    parsed_port: typing.Optional[int] = normalize_port(port, scheme)
  File "D:\dev\project\graduationProject\craw\new\MediaCrawler\myvenv\lib\site-packages\httpx\_urlparse.py", line 341, in normalize_port
    raise InvalidURL("Invalid port")
httpx.InvalidURL: Invalid port

系统:win10
python:3.9

**Comment by kevinWangSheng** [comment]
这个如何解决呢？不管是ks，dy都是报这个错误
