### ISSUE TITLE
asyncio.exceptions.CancelledError

### ISSUE THREAD

**Issue by ugzhu** [NanmiCoder/MediaCrawler#138]
每次爬了一个多小时就会中断，MAX_CONCURRENCY_NUM = 20

Traceback (most recent call last):
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/anyio/_core/_tasks.py", line 115, in fail_after
    yield cancel_scope
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpcore/_backends/anyio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/anyio/streams/tls.py", line 205, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/anyio/streams/tls.py", line 147, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 1123, in receive
    await self._protocol.read_event.wait()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpcore/_backends/anyio.py", line 36, in read
    return b""
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/anyio/_core/_tasks.py", line 118, in fail_after
    raise TimeoutError
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpx/_transports/default.py", line 239, in __aiter__
    async for part in self._httpcore_stream:
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 347, in __aiter__
    async for part in self._stream:
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpcore/_async/http11.py", line 325, in __aiter__
    raise exc
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpcore/_async/http11.py", line 317, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpcore/_async/http11.py", line 186, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpcore/_async/http11.py", line 200, in _receive_event
    data = await self._network_stream.read(
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpcore/_backends/anyio.py", line 36, in read
    return b""
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 63, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "main.py", line 57, in main
    await crawler.start()
  File "/Users/yzhu/workspace/repo/MediaCrawler/media_platform/xhs/core.py", line 84, in start
    await self.search()
  File "/Users/yzhu/workspace/repo/MediaCrawler/media_platform/xhs/core.py", line 122, in search
    await self.batch_get_note_comments(note_id_list)
  File "/Users/yzhu/workspace/repo/MediaCrawler/media_platform/xhs/core.py", line 171, in batch_get_note_comments
    await asyncio.gather(*task_list)
  File "/Users/yzhu/workspace/repo/MediaCrawler/media_platform/xhs/core.py", line 177, in get_comments
    all_comments = await self.xhs_client.get_note_all_comments(note_id=note_id, crawl_interval=random.random())
  File "/Users/yzhu/workspace/repo/MediaCrawler/media_platform/xhs/client.py", line 190, in get_note_all_comments
    comments_res = await self.get_note_comments(note_id, comments_cursor)
  File "/Users/yzhu/workspace/repo/MediaCrawler/media_platform/xhs/client.py", line 153, in get_note_comments
    return await self.get(uri, params)
  File "/Users/yzhu/workspace/repo/MediaCrawler/media_platform/xhs/client.py", line 76, in get
    return await self.request(method="GET", url=f"{self._host}{final_uri}", headers=headers)
  File "/Users/yzhu/workspace/repo/MediaCrawler/media_platform/xhs/client.py", line 58, in request
    response = await client.request(
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpx/_client.py", line 1631, in send
    raise exc
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpx/_client.py", line 1625, in send
    await response.aread()
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpx/_models.py", line 909, in aread
    self._content = b"".join([part async for part in self.aiter_bytes()])
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpx/_models.py", line 909, in <listcomp>
    self._content = b"".join([part async for part in self.aiter_bytes()])
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpx/_models.py", line 927, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpx/_models.py", line 985, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpx/_client.py", line 146, in __aiter__
    async for chunk in self._stream:
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpx/_transports/default.py", line 240, in __aiter__
    yield part
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/yzhu/workspace/repo/MediaCrawler/venv/lib/python3.8/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout

**Comment by NanmiCoder** [comment]
TimeoutError，超时了，平台方已经拒绝请求了
