### ISSUE TITLE
ValueError: Set of coroutines/Futures is empty.

### ISSUE THREAD

**Issue by qwertyuiopasdfghjklzxcn** [NanmiCoder/MediaCrawler#151]
(thor) E:\MediaCrawler-main>python main.py --platform dy --lt qrcode --type search  
2024-03-12  22:06:09 MediaCrawler INFO [DouYinCrawler.search] Begin search douyin keywords 
2024-03-12  22:06:09 MediaCrawler INFO [DouYinCrawler.search] Current keyword: 心灵抚慰 
2024-03-12  22:06:11 httpx INFO HTTP Request: GET https://www.douyin.com/aweme/v1/web/general/search/single/?keyword=%E5%BF%83%E7%81%B5%E6%8A%9A%E6%85%B0&search_channel=aweme_general&sort_type=0&publish_time=0&search_source=normal_search&query_correct_type=1&is_filter_search=0&offset=0&count=10&device_platform=webapp&aid=6383&channel=channel_pc_web&cookie_enabled=true&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&os_name=Windows&os_version=10&engine_version=109.0&platform=PC&screen_width=1920&screen_height=1200&X-Bogus=DFSzswSL7mXANnEftLwbMU9WcBJO "HTTP/1.1 200 OK" 
2024-03-12  22:06:11 MediaCrawler ERROR [DouYinCrawler.search] search douyin keyword: 心灵抚慰 failed 
2024-03-12  22:06:11 MediaCrawler INFO [DouYinCrawler.search] keyword:心灵抚慰, aweme_list:[] 
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\23968\Anaconda3\envs\thor\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "main.py", line 53, in main
    await crawler.start()
  File "E:\MediaCrawler-main\media_platform\douyin\core.py", line 74, in start
    await self.search()
  File "E:\MediaCrawler-main\media_platform\douyin\core.py", line 105, in search
    await self.batch_get_note_comments(aweme_list)
  File "E:\MediaCrawler-main\media_platform\douyin\core.py", line 138, in batch_get_note_comments
    await asyncio.wait(task_list)
  File "C:\Users\23968\Anaconda3\envs\thor\lib\asyncio\tasks.py", line 413, in wait
    raise ValueError('Set of coroutines/Futures is empty.')
ValueError: Set of coroutines/Futures is empty.

作者大大，出现了这样的错误

**Comment by NanmiCoder** [comment]
拉去新代码，之前的因为抖音这边对中文搜索做了限制
