### ISSUE TITLE
小红书 扫码成功后 报错

### ISSUE THREAD

**Issue by bowerliu** [NanmiCoder/MediaCrawler#16]
小红书 扫码后 报错

如下：
2023-07-08  18:04:13 root INFO Begin login xiaohongshu by qrcode ... 
2023-07-08  18:04:23 root INFO waiting for scan code login, remaining time is 20s 
Traceback (most recent call last):
  File "/Users/username/work/github_test/MediaCrawler/main.py", line 58, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/username/work/github_test/MediaCrawler/main.py", line 39, in main
    await crawler.start()
  File "/Users/username/work/github_test/MediaCrawler/media_platform/xhs/core.py", line 82, in start
    await login_obj.begin()
  File "/Users/username/work/github_test/MediaCrawler/media_platform/xhs/login.py", line 48, in begin
    await self.login_by_qrcode()
  File "/Users/username/work/github_test/MediaCrawler/media_platform/xhs/login.py", line 155, in login_by_qrcode
    login_flag: bool = await self.check_login_state(no_logged_in_session)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1271e2ef0 state=finished returned bool>]

**Comment by xtuyaowu** [comment]
我跑起来了用的python3.9

**Comment by NanmiCoder** [comment]
hello，看日志中的提示情况应该是达到了重试判断登录的最大次数，请确认扫码过程中的耗时，我这边目前小红书还是能正常扫码登录的。

**Comment by NanmiCoder** [comment]
fix it

https://github.com/NanmiCoder/MediaCrawler/blob/dad8d56ab5a282f5560e12a36286eebfc6cb0082/media_platform/xhs/login.py#L165-L170
