### ISSUE TITLE
Help me: 项目启动报错

### ISSUE THREAD

**Issue by tanpenggood** [NanmiCoder/MediaCrawler#22]
|software|version|
|---|---|
|OS|mac|
|python|3.11|

```
$ python main.py --platform xhs --lt qrcode
Traceback (most recent call last):
  File "/Users/xxx/tp-code/MediaCrawler/main.py", line 8, in <module>
    from media_platform.douyin import DouYinCrawler
  File "/Users/xxx/tp-code/MediaCrawler/media_platform/douyin/__init__.py", line 1, in <module>
    from .core import DouYinCrawler
  File "/Users/xxx/tp-code/MediaCrawler/media_platform/douyin/core.py", line 17, in <module>
    from .login import DouYinLogin
  File "/Users/xxx/tp-code/MediaCrawler/media_platform/douyin/login.py", line 6, in <module>
    import aioredis
  File "/Users/xxx/miniconda3/lib/python3.11/site-packages/aioredis/__init__.py", line 1, in <module>
    from aioredis.client import Redis, StrictRedis
  File "/Users/xxx/miniconda3/lib/python3.11/site-packages/aioredis/client.py", line 32, in <module>
    from aioredis.connection import (
  File "/Users/xxx/miniconda3/lib/python3.11/site-packages/aioredis/connection.py", line 33, in <module>
    from .exceptions import (
  File "/Users/xxx/miniconda3/lib/python3.11/site-packages/aioredis/exceptions.py", line 14, in <module>
    class TimeoutError(asyncio.TimeoutError, builtins.TimeoutError, RedisError):
TypeError: duplicate base class TimeoutError
```

**Comment by NanmiCoder** [comment]
看样子是redis连接超时了，可以检查你的redis是否设置密码了以及密码是否正确。

**Comment by tanpenggood** [comment]
我在本地6379端口启动的redis，配置如下：

`config/db_config.py`
```
# redis config
REDIS_DB_HOST = "redis://127.0.0.1"  # your redis host
REDIS_DB_PWD = ""  # your redis password

# mysql config
RELATION_DB_URL = "mysql://root:youdbpassword@localhost:3306/media_crawler"

# save data to database option
IS_SAVED_DATABASED = False  # if you want to save data to database, set True
```

**Comment by NanmiCoder** [comment]
浅看了一下`aioredis`中Client视乎对密码是必填的，意味着你需要先设置下 `Redis Server` 配置文件的密码，再在db_config.py中配置密码，不能填空字符。

**Comment by tanpenggood** [comment]
我给redis设置了密码 123456，
再次`python main.py --platform xhs --lt qrcode`
仍然是上面的错误。

**Comment by NanmiCoder** [comment]
找到原因了，这是一个`aioredis`的bug，对`python3.11`版本不支持了，稍后我会用`redis`模块来替换aioredis，https://github.com/aio-libs/aioredis-py/issues/1409

**Comment by tanpenggood** [comment]
太棒了！ 我拉下来，因为这个问题好几天都没启动😂

**Comment by tanpenggood** [comment]
刚刚还特意用`redis-test.py`，做连接redis的测试，发现报错同样和上面一样。
```python
import config
import aioredis

if __name__ == '__main__':
    redis_obj = aioredis.from_url(url=config.REDIS_DB_HOST, password=config.REDIS_DB_PWD, decode_responses=True)
    value = redis_obj.get("hello")
    print(value)
```

这个坎儿算是过去了，我还以为电脑出问题了😆。

**Comment by NanmiCoder** [comment]
该问题已经修复，已将`aioredis`替换为官方的`redis`实现，麻烦你拉下最新代码跑跑看，能否启动起来。

**Comment by tanpenggood** [comment]
OK!

|software | version|
|-- | --|
|OS | mac|
|python | 3.11|

```
$ pip install -r requirements.txt

...

$ python main.py --platform xhs --lt qrcode
2023-07-30  21:03:41 MediaCrawler INFO Begin create browser context ... 
2023-07-30  21:03:49 MediaCrawler INFO Begin create xiaohongshu API client ... 
2023-07-30  21:03:49 MediaCrawler INFO begin to ping xhs... 
2023-07-30  21:03:50 MediaCrawler INFO Begin search xiaohongshu keywords 
2023-07-30  21:03:50 MediaCrawler INFO Current keyword: 健身 
...
```

**Comment by tanpenggood** [comment]
`LOGIN_TYPE = 'cookie'`时, `COOKIES`我应该怎么设置呢？

**Comment by NanmiCoder** [comment]
> `LOGIN_TYPE = 'cookie'`时, `COOKIES`我应该怎么设置呢？

https://github.com/NanmiCoder/MediaCrawler/blob/1d3c2359e0f4e93029d1bfbaf2d135f1139bdfa3/config/base_config.py#L4-L5
