### ISSUE TITLE
执行python db.py报错

### ISSUE THREAD

**Issue by AI-Study-Han** [NanmiCoder/MediaCrawler#236]
2024-04-16  14:42:37 MediaCrawler INFO [init_db] start init mediacrawler db connect object
<function parse_mysql_url at 0x0000017C60FC0EA0>
2024-04-16  14:42:37 MediaCrawler INFO [init_db] end init mediacrawler db connect object
Exception ignored in: <function Connection.__del__ at 0x0000017C61C1C540>
Traceback (most recent call last):
  File "D:\Anaconda3\envs\mc\Lib\site-packages\aiomysql\connection.py", line 1131, in __del__
    self.close()
  File "D:\Anaconda3\envs\mc\Lib\site-packages\aiomysql\connection.py", line 339, in close
    self._writer.transport.close()
  File "D:\Anaconda3\envs\mc\Lib\asyncio\proactor_events.py", line 109, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\Anaconda3\envs\mc\Lib\asyncio\base_events.py", line 793, in call_soon
    self._check_closed()
  File "D:\Anaconda3\envs\mc\Lib\asyncio\base_events.py", line 540, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

执行python db.py报错是什么原因啊

**Comment by NanmiCoder** [comment]
请拉取新的代码尝试，新代码不需要初始化db了，需要你手工的在schema这个目录下把建表语句在mysql下执行
