### ISSUE TITLE
我在使用cookie登录抖音后遇到了execjs._exceptions.RuntimeUnavailableError: Could not find an available JavaScript runtime.的错误

### ISSUE THREAD

**Issue by InMyDreammer** [NanmiCoder/MediaCrawler#29]
详细的报错信息如下：(base) yyyy:~/Union/MediaCrawler$ python main.py --platform dy --lt cookie
/yyyy/MediaCrawler/main.py:51: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(main())
2023-08-11  15:08:42 MediaCrawler INFO Begin login douyin by cookie ... 
2023-08-11  15:08:48 MediaCrawler INFO login finished then check login state ... 
2023-08-11  15:08:48 MediaCrawler INFO Login successful then wait for 5 seconds redirect ... 
2023-08-11  15:08:53 MediaCrawler INFO Begin search douyin keywords 
2023-08-11  15:08:53 MediaCrawler INFO Current keyword: 健身 
Traceback (most recent call last):
  File "/yyyy/MediaCrawler/main.py", line 51, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/yyyy/anaconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/yyyy/MediaCrawler/main.py", line 45, in main
    await crawler.start()
  File "/yyyy/MediaCrawler/media_platform/douyin/core.py", line 66, in start
    await self.search()
  File "/yyyy/MediaCrawler/media_platform/douyin/core.py", line 79, in search
    posts_res = await self.dy_client.search_info_by_keyword(keyword=keyword,
  File "/yyyy/MediaCrawler/media_platform/douyin/client.py", line 129, in search_info_by_keyword
    return await self.get("/aweme/v1/web/general/search/single/", params, headers=headers)
  File "/yyyy/MediaCrawler/media_platform/douyin/client.py", line 78, in get
    await self.__process_req_params(params, headers)
  File "/yyyy/MediaCrawler/media_platform/douyin/client.py", line 38, in __process_req_params
    douyin_js_obj = execjs.compile(open('libs/douyin.js').read())
  File "/yyyy/anaconda3/lib/python3.10/site-packages/execjs/__init__.py", line 61, in compile
    return get().compile(source, cwd)
  File "/yyyy/anaconda3/lib/python3.10/site-packages/execjs/_runtimes.py", line 21, in get
    return get_from_environment() or _find_available_runtime()
  File "/yyyy/anaconda3/lib/python3.10/site-packages/execjs/_runtimes.py", line 49, in _find_available_runtime
    raise exceptions.RuntimeUnavailableError("Could not find an available JavaScript runtime.")
execjs._exceptions.RuntimeUnavailableError: Could not find an available JavaScript runtime.

**Comment by NanmiCoder** [comment]
看样子是没有JS的运行环境，你安装一下nodejs试试：https://nodejs.org/zh-cn/download

**Comment by InMyDreammer** [comment]
> 看样子是没有JS的运行环境，你安装一下nodejs试试：https://nodejs.org/zh-cn/download

服务器上可以安装nodejs吗

**Comment by NanmiCoder** [comment]
> > 看样子是没有JS的运行环境，你安装一下nodejs试试：https://nodejs.org/zh-cn/download
> 
> 服务器上可以安装nodejs吗

可以的

**Comment by InMyDreammer** [comment]
安装node.js后报错：
Traceback (most recent call last):
  File "/yyyy/Union/MediaCrawler/main.py", line 51, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/yyyy/anaconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/yyyy/Union/MediaCrawler/main.py", line 45, in main
    await crawler.start()
  File "/yyyy/Union/MediaCrawler/media_platform/douyin/core.py", line 66, in start
    await self.search()
  File "/yyyy/Union/MediaCrawler/media_platform/douyin/core.py", line 79, in search
    posts_res = await self.dy_client.search_info_by_keyword(keyword=keyword,
  File "/yyyy/Union/MediaCrawler/media_platform/douyin/client.py", line 129, in search_info_by_keyword
    return await self.get("/aweme/v1/web/general/search/single/", params, headers=headers)
  File "/yyyy/Union/MediaCrawler/media_platform/douyin/client.py", line 78, in get
    await self.__process_req_params(params, headers)
  File "/yyyy/Union/MediaCrawler/media_platform/douyin/client.py", line 56, in __process_req_params
    "webid": douyin_js_obj.call("get_web_id"),
  File "/yyyy/anaconda3/lib/python3.10/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "/yyyy/anaconda3/lib/python3.10/site-packages/execjs/_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "/yyyy/anaconda3/lib/python3.10/site-packages/execjs/_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "/yyyy/anaconda3/lib/python3.10/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "/yyyy/anaconda3/lib/python3.10/site-packages/execjs/_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "/yyyy/anaconda3/lib/python3.10/site-packages/execjs/_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null

**Comment by InMyDreammer** [comment]
> > > 看样子是没有JS的运行环境，你安装一下nodejs试试：https://nodejs.org/zh-cn/download
> > 
> > 
> > 服务器上可以安装nodejs吗
> 
> 可以的

安装node.js后报错：
Traceback (most recent call last):
File "/yyyy/Union/MediaCrawler/main.py", line 51, in
asyncio.get_event_loop().run_until_complete(main())
File "/yyyy/anaconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
return future.result()
File "/yyyy/Union/MediaCrawler/main.py", line 45, in main
await crawler.start()
File "/yyyy/Union/MediaCrawler/media_platform/douyin/core.py", line 66, in start
await self.search()
File "/yyyy/Union/MediaCrawler/media_platform/douyin/core.py", line 79, in search
posts_res = await self.dy_client.search_info_by_keyword(keyword=keyword,
File "/yyyy/Union/MediaCrawler/media_platform/douyin/client.py", line 129, in search_info_by_keyword
return await self.get("/aweme/v1/web/general/search/single/", params, headers=headers)
File "/yyyy/Union/MediaCrawler/media_platform/douyin/client.py", line 78, in get
await self.__process_req_params(params, headers)
File "/yyyy/Union/MediaCrawler/media_platform/douyin/client.py", line 56, in __process_req_params
"webid": douyin_js_obj.call("get_web_id"),
File "/yyyy/anaconda3/lib/python3.10/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
return self._call(name, *args)
File "/yyyy/anaconda3/lib/python3.10/site-packages/execjs/_external_runtime.py", line 92, in _call
return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
File "/yyyy/anaconda3/lib/python3.10/site-packages/execjs/_external_runtime.py", line 78, in eval
return self.exec(code)
File "/yyyy/anaconda3/lib/python3.10/site-packages/execjs/abstract_runtime_context.py", line 18, in exec
return self.exec(source)
File "/yyyy/anaconda3/lib/python3.10/site-packages/execjs/_external_runtime.py", line 88, in exec
return self._extract_result(output)
File "/yyyy/anaconda3/lib/python3.10/site-packages/execjs/_external_runtime.py", line 167, in _extract_result
raise ProgramError(value)
execjs._exceptions.ProgramError: TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null

**Comment by NanmiCoder** [comment]
方便把你的系统环境告知一下吗，目前我这里无法复现该问题。

**Comment by InMyDreammer** [comment]
> 方便把你的系统环境告知一下吗，目前我这里无法复现该问题。

可以的，Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

**Comment by InMyDreammer** [comment]
> 方便把你的系统环境告知一下吗，目前我这里无法复现该问题。

我在win10本地跑代码报错变了，变成PS E:\pythonProject2\MediaCrawler> python main.py --platform dy --lt cookie
2023-08-11  18:20:33 MediaCrawler INFO Begin login douyin by cookie ... 
2023-08-11  18:20:39 MediaCrawler INFO login finished then check login state ... 
2023-08-11  18:20:39 MediaCrawler INFO Login successful then wait for 5 seconds redirect ... 
2023-08-11  18:20:44 MediaCrawler INFO Begin search douyin keywords 
2023-08-11  18:20:44 MediaCrawler INFO Current keyword: 健身 
Traceback (most recent call last):
  File "E:\pythonProject2\MediaCrawler\main.py", line 51, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "E:\pythonProject2\MediaCrawler\main.py", line 45, in main
    await crawler.start()
  File "E:\pythonProject2\MediaCrawler\media_platform\douyin\core.py", line 66, in start
    await self.search()
  File "E:\pythonProject2\MediaCrawler\media_platform\douyin\core.py", line 79, in search
    posts_res = await self.dy_client.search_info_by_keyword(keyword=keyword,
  File "E:\pythonProject2\MediaCrawler\media_platform\douyin\client.py", line 129, in search_info_by_keyword
    return await self.get("/aweme/v1/web/general/search/single/", params, headers=headers)
  File "E:\pythonProject2\MediaCrawler\media_platform\douyin\client.py", line 78, in get
    await self.__process_req_params(params, headers)
  File "E:\pythonProject2\MediaCrawler\media_platform\douyin\client.py", line 56, in __process_req_params
    "webid": douyin_js_obj.call("get_web_id"),
  File "E:\pythonProject2\venv\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "E:\pythonProject2\venv\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "E:\pythonProject2\venv\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "E:\pythonProject2\venv\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "E:\pythonProject2\venv\lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "E:\pythonProject2\venv\lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: 缺少 ';'

**Comment by NanmiCoder** [comment]
安装的是 `PyExecJS==1.5.1` 这个库么

**Comment by InMyDreammer** [comment]
> 安装的是 `PyExecJS==1.5.1` 这个库么

是这个库

**Comment by NanmiCoder** [comment]
你先不跑这个项目 看看你使用这个库能正常使用么，先排除一下 因为没有其他人反应过改问题

**Comment by InMyDreammer** [comment]
> 你先不跑这个项目 看看你使用这个库能正常使用么，先排除一下 因为没有其他人反应过改问题

解决好了，安装nodejs 重启pycharm 就可以了。
大佬我想问问能将输出的数据输出到指定的本地csv 文件吗

**Comment by NanmiCoder** [comment]
我在这个issue中回复了，你看下 
https://github.com/NanmiCoder/MediaCrawler/issues/28#issuecomment-1674268075

**Comment by wapping** [comment]
ubuntu上遇到同样的问题，通过两行命令解决了
`sudo apt update
sudo apt install nodejs npm`
