### ISSUE TITLE
为什么访问小红书地址 reset了？

### ISSUE THREAD

**Issue by lzy350593418** [NanmiCoder/MediaCrawler#296]
D:\pytcode\MediaCrawler-main>python main.py --platform xhs --lt cookie --type search
2024-06-12 16:40:38 [MainThread] MediaCrawler INFO (core.py:252) - [XiaoHongShuCrawler.launch_browser] Begin create browser context ...
Traceback (most recent call last):
  File "D:\pytcode\MediaCrawler-main\main.py", line 48, in <module>
    asyncio.run(main())
  File "D:\python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\pytcode\MediaCrawler-main\main.py", line 40, in main
    await crawler.start()
  File "D:\pytcode\MediaCrawler-main\media_platform\xhs\core.py", line 58, in start
    await self.context_page.goto(self.index_url)
  File "D:\python310\lib\site-packages\playwright\async_api\_generated.py", line 8612, in goto
    await self._impl_obj.goto(
  File "D:\python310\lib\site-packages\playwright\_impl\_page.py", line 500, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "D:\python310\lib\site-packages\playwright\_impl\_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "D:\python310\lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "D:\python310\lib\site-packages\playwright\_impl\_connection.py", line 509, in wrap_api_call
    return await cb()
  File "D:\python310\lib\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._errors.Error: net::ERR_CONNECTION_RESET at https://www.xiaohongshu.com/
2024-06-12 16:40:40 [MainThread] asyncio ERROR (base_events.py:1747) - Task was destroyed but it is pending!
task: <Task cancelling name='Task-2' coro=<ExpiringLocalCache._start_clear_cron() running at D:\pytcode\MediaCrawler-main\cache\local_cache.py:101>>
sys:1: RuntimeWarning: coroutine 'ExpiringLocalCache._start_clear_cron' was never awaited
2024-06-12 16:40:40 [MainThread] asyncio ERROR (base_events.py:1747) - Task was destroyed but it is pending!
task: <Task cancelling name='Task-1' coro=<ExpiringLocalCache._start_clear_cron() running at D:\pytcode\MediaCrawler-main\cache\local_cache.py:101>>

**Comment by NanmiCoder** [comment]
挂了proxy吗？

**Comment by lzy350593418** [comment]
> 挂了proxy吗？

没有呀，而且我用了下，发现调用谷歌或者它自身的chromium浏览器，小红书的地址访问变得好慢，还被小红书进行了人工验证

**Comment by lzy350593418** [comment]
> 挂了proxy吗？

可以把xhs client那串代码copy过来 自己构造，用后端的方式去进行关键词搜索吗？我想这样尝试一下，playwright调用浏览器特别缓慢且迟钝，你有遇到过这种情况吗

**Comment by lzy350593418** [comment]
还有一个情况就是 执行search  关键词搜索的时候，浏览器直接崩了，程序即刻停止，我看那么多人在用，代码也没问题的呀，你有遇到这种情况吗

**Comment by dmortem** [comment]
从昨晚开始，小红书的search功能也一直返回空，是不是小红书搜索api发生了什么变化

**Comment by NanmiCoder** [comment]
> > 挂了proxy吗？
> 
> 可以把xhs client那串代码copy过来 自己构造，用后端的方式去进行关键词搜索吗？我想这样尝试一下，playwright调用浏览器特别缓慢且迟钝，你有遇到过这种情况吗

没有哦，基于大家的反馈来看，xhs是最稳定的

**Comment by lzy350593418** [comment]
> Owner

公司挂了proxy....现在好了，感谢。
