### ISSUE TITLE
Invalid port Bug

### ISSUE THREAD

**Issue by Qxxxx** [NanmiCoder/MediaCrawler#3]
报以下错误

```
Begin search xiaohongshu keywords:  健身
Traceback (most recent call last):
  File "/home/MediaCrawler/env/lib/python3.8/site-packages/httpx/_urlparse.py", line 339, in normalize_port
    port_as_int = int(port)
ValueError: invalid literal for int() with base 10: ':1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 35, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "main.py", line 30, in main
    await crawler.start()
  File "/home/MediaCrawler/media_platform/xhs/core.py", line 70, in start
    note_res = await self.search_posts()
  File "/home/MediaCrawler/media_platform/xhs/core.py", line 134, in search_posts
    posts_res = await self.xhs_client.get_note_by_keyword(keyword=self.keywords)
  File "/home/MediaCrawler/media_platform/xhs/client.py", line 110, in get_note_by_keyword
    return await self.post(uri, data)
  File "/home/MediaCrawler/media_platform/xhs/client.py", line 77, in post
    return await self.request(method="POST", url=f"{self._host}{uri}",
  File "/home/MediaCrawler/media_platform/xhs/client.py", line 53, in request
    async with httpx.AsyncClient(proxies=self.proxies) as client:
  File "/home/MediaCrawler/env/lib/python3.8/site-packages/httpx/_client.py", line 1408, in __init__
    self._mounts: typing.Dict[URLPattern, typing.Optional[AsyncBaseTransport]] = {
  File "/home/MediaCrawler/env/lib/python3.8/site-packages/httpx/_client.py", line 1409, in <dictcomp>
    URLPattern(key): None
  File "/home/MediaCrawler/env/lib/python3.8/site-packages/httpx/_utils.py", line 397, in __init__
    url = URL(pattern)
  File "/home/MediaCrawler/env/lib/python3.8/site-packages/httpx/_urls.py", line 113, in __init__
    self._uri_reference = urlparse(url, **kwargs)
  File "/home/MediaCrawler/env/lib/python3.8/site-packages/httpx/_urlparse.py", line 246, in urlparse
    parsed_port: typing.Optional[int] = normalize_port(port, scheme)
  File "/home/MediaCrawler/env/lib/python3.8/site-packages/httpx/_urlparse.py", line 341, in normalize_port
    raise InvalidURL("Invalid port")
httpx.InvalidURL: Invalid port
```

**Comment by NanmiCoder** [comment]
如果是传入了代理参数的话，检查下代理的格式是否准确,或者暂时不要用代理
代理功能目前我还未测试，估计很鸡肋，后续会增加IP代理池的feature.

**Comment by Qxxxx** [comment]
没有传入代理，就按照readme 一模一样的命令，报了这个错误

**Comment by NanmiCoder** [comment]
方便把你的电脑环境发一下吗，我在windows和mac上没有复现这个问题

**Comment by NanmiCoder** [comment]
> 有可能和公司的代理有关系，我回家再试一试好了，对了方便加微信吗？

晚上下班了我整个QQ讨论群, 大家有疑问群里沟通方便些~

**Comment by NanmiCoder** [comment]
你在本地的电脑搞定了吗? 搞定的话我把issue关了，你说的小红书批量创作的功能可以看下最新提交的代码，可以实现了完全自动完成登录+获取笔记的功能

**Comment by Qxxxx** [comment]
本地确实是没有问题，可能是公司网络的问题。创作的话可能应该用的是，https://creator.xiaohongshu.com/ 这个网站。你后续加的解决方案是，可能属于批量爬虫，但你用playwright的解决方案还是很有帮助。之所以需要用一些小红书爬虫，核心原因是，我做了一个网站 www.yier.ai 这个网站里小红书功能是最受欢迎的，所以准备集成一下爬虫功能增强一下。

**Comment by NanmiCoder** [comment]
OKOK

**Comment by dfinity-web3** [comment]
我的也遇到了这个问题，是不是要在服务器上才可以呢？
