### ISSUE TITLE
python main.py --platform dy --lt qrcode 失败

### ISSUE THREAD

**Issue by dfinity-web3** [NanmiCoder/MediaCrawler#30]
执行命令 python main.py --platform dy --lt qrcode 
其中 --lt  后面能跟的参数都尝试了，结果总是错误：
Traceback (most recent call last):
  File "C:\Users\nuc8\Downloads\MediaCrawler-main\MediaCrawler-main\main.py", line 51, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\nuc8\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\nuc8\Downloads\MediaCrawler-main\MediaCrawler-main\main.py", line 45, in main
    await crawler.start()
  File "C:\Users\nuc8\Downloads\MediaCrawler-main\MediaCrawler-main\media_platform\douyin\core.py", line 66, in start
    await self.search()
  File "C:\Users\nuc8\Downloads\MediaCrawler-main\MediaCrawler-main\media_platform\douyin\core.py", line 79, in search
    posts_res = await self.dy_client.search_info_by_keyword(keyword=keyword,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nuc8\Downloads\MediaCrawler-main\MediaCrawler-main\media_platform\douyin\client.py", line 129, in search_info_by_keyword
    return await self.get("/aweme/v1/web/general/search/single/", params, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nuc8\Downloads\MediaCrawler-main\MediaCrawler-main\media_platform\douyin\client.py", line 78, in get
    await self.__process_req_params(params, headers)
  File "C:\Users\nuc8\Downloads\MediaCrawler-main\MediaCrawler-main\media_platform\douyin\client.py", line 56, in __process_req_params
    "webid": douyin_js_obj.call("get_web_id"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nuc8\AppData\Local\Programs\Python\Python311\Lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nuc8\AppData\Local\Programs\Python\Python311\Lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nuc8\AppData\Local\Programs\Python\Python311\Lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\nuc8\AppData\Local\Programs\Python\Python311\Lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nuc8\AppData\Local\Programs\Python\Python311\Lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nuc8\AppData\Local\Programs\Python\Python311\Lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: 缺少 ';'

**Comment by NanmiCoder** [comment]
看下这个 issue https://github.com/NanmiCoder/MediaCrawler/issues/29#issuecomment-1674584856
