### ISSUE TITLE
抖音无头浏览器采集帖子a_bogus异常

### ISSUE THREAD

**Issue by SilenceXSJ** [NanmiCoder/MediaCrawler#352]
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1527, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\MediaCrawler-main\MediaCrawler-main\main.py", line 49, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\silen\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\MediaCrawler-main\MediaCrawler-main\main.py", line 40, in main
    await crawler.start()
  File "D:\MediaCrawler-main\MediaCrawler-main\media_platform\douyin\core.py", line 69, in start
    await self.get_specified_awemes()
  File "D:\MediaCrawler-main\MediaCrawler-main\media_platform\douyin\core.py", line 124, in get_specified_awemes
    aweme_details = await asyncio.gather(*task_list)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MediaCrawler-main\MediaCrawler-main\media_platform\douyin\core.py", line 134, in get_aweme_detail
    return await self.dy_client.get_video_by_id(aweme_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MediaCrawler-main\MediaCrawler-main\media_platform\douyin\client.py", line 176, in get_video_by_id
    res = await self.get("/aweme/v1/web/aweme/detail/", params, headers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MediaCrawler-main\MediaCrawler-main\media_platform\douyin\client.py", line 101, in get
    await self.__process_req_params(params, headers)
  File "D:\MediaCrawler-main\MediaCrawler-main\media_platform\douyin\client.py", line 80, in __process_req_params
    a_bogus = await get_a_bogus(query_string, post_data, headers["User-Agent"], self.playwright_page)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MediaCrawler-main\MediaCrawler-main\media_platform\douyin\help.py", line 37, in get_a_bogus
    return await get_a_bogus_from_playright(params, post_data, user_agent, page)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MediaCrawler-main\MediaCrawler-main\media_platform\douyin\help.py", line 48, in get_a_bogus_from_playright
    a_bogus = await page.evaluate(
              ^^^^^^^^^^^^^^^^^^^^
  File "D:\MediaCrawler-main\MediaCrawler-main\.venv\Lib\site-packages\playwright\async_api\_generated.py", line 8119, in evaluate
    await self._impl_obj.evaluate(
  File "D:\MediaCrawler-main\MediaCrawler-main\.venv\Lib\site-packages\playwright\_impl\_page.py", line 416, in evaluate
    return await self._main_frame.evaluate(expression, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MediaCrawler-main\MediaCrawler-main\.venv\Lib\site-packages\playwright\_impl\_frame.py", line 278, in evaluate
    await self._channel.send(
  File "D:\MediaCrawler-main\MediaCrawler-main\.venv\Lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MediaCrawler-main\MediaCrawler-main\.venv\Lib\site-packages\playwright\_impl\_connection.py", line 509, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "D:\MediaCrawler-main\MediaCrawler-main\.venv\Lib\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._errors.Error: TypeError: Cannot read properties of undefined (reading 'init')
    at eval (eval at evaluate (:226:30), <anonymous>:1:42)
    at UtilityScript.evaluate (<anonymous>:233:19)
    at UtilityScript.<anonymous> (<anonymous>:1:44)

**Comment by NanmiCoder** [comment]
没有复现该问题
