### ISSUE TITLE
为什么小红书的帖子照片/视频，没有自动下载，但是只给了个链接，是需要自己去实现下载评论的同时顺便下载照片视频吗

### ISSUE THREAD

**Issue by 707806032** [NanmiCoder/MediaCrawler#410]

**Comment by NanmiCoder** [comment]
https://github.com/NanmiCoder/MediaCrawler/blob/da12df711313e082a043338631b25af1fb4ca19e/config/base_config.py#L46

**Comment by 707806032** [comment]
> https://github.com/NanmiCoder/MediaCrawler/blob/da12df711313e082a043338631b25af1fb4ca19e/config/base_config.py#L46

我设置了True但是没有下载照片或者视频

**Comment by jeffyeylw** [comment]
照片被顺利下载到Image文件，但是视频会出现超时报错，即使调整了timeout时间也没有正常下载视频
![image](https://github.com/user-attachments/assets/eb03e6c5-c9bb-486e-9a3c-fc687399e8c0)

报错：Traceback (most recent call last):
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpcore\_backends\anyio.py", line 34, 
in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\anyio\_backends\_asyncio.py", line 1238, in receive
    raise self._protocol.exception from None
anyio.BrokenResourceError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpx\_transports\default.py", line 239, in __aiter__
    async for part in self._httpcore_stream:
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpcore\_async\connection_pool.py", line 347, in __aiter__
    async for part in self._stream:
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpcore\_async\http11.py", line 325, in __aiter__
    raise exc
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpcore\_async\http11.py", line 317, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpcore\_async\http11.py", line 186, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpcore\_async\http11.py", line 200, in _receive_event
    data = await self._network_stream.read(
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpcore\_backends\anyio.py", line 36, 
in read
    return b""
  File "C:\Users\user\.conda\envs\mediacrawler\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\叶力维-实习\爬虫\MediaCrawler\main.py", line 67, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\user\.conda\envs\mediacrawler\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\user\Desktop\叶力维-实习\爬虫\MediaCrawler\main.py", line 56, in main
    await crawler.start()
  File "C:\Users\user\Desktop\叶力维-实习\爬虫\MediaCrawler\media_platform\xhs\core.py", line 92, in start
    await self.search()
  File "C:\Users\user\Desktop\叶力维-实习\爬虫\MediaCrawler\media_platform\xhs\core.py", line 150, in search
    await self.get_notice_media(note_detail)
  File "C:\Users\user\Desktop\叶力维-实习\爬虫\MediaCrawler\media_platform\xhs\core.py", line 345, in get_notice_media
    await self.get_notice_video(note_detail)
  File "C:\Users\user\Desktop\叶力维-实习\爬虫\MediaCrawler\media_platform\xhs\core.py", line 392, in get_notice_video
    content = await self.xhs_client.get_note_media(url)
  File "C:\Users\user\Desktop\叶力维-实习\爬虫\MediaCrawler\media_platform\xhs\client.py", line 154, in 
get_note_media
    response = await client.request("GET", url, timeout=self.timeout)
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpx\_client.py", line 1631, in send  
    raise exc
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpx\_client.py", line 1625, in send  
    await response.aread()
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpx\_models.py", line 909, in aread  
    self._content = b"".join([part async for part in self.aiter_bytes()])
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpx\_models.py", line 909, in <listcomp>
    self._content = b"".join([part async for part in self.aiter_bytes()])
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpx\_models.py", line 927, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpx\_models.py", line 985, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpx\_client.py", line 146, in __aiter__
    async for chunk in self._stream:
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpx\_transports\default.py", line 240, in __aiter__
    yield part
  File "C:\Users\user\.conda\envs\mediacrawler\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\user\.conda\envs\mediacrawler\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadError
