### ISSUE TITLE
爬取抖音评论相关

### ISSUE THREAD

**Issue by Windsland52** [NanmiCoder/MediaCrawler#431]
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\github\MediaCrawler\main.py", line 53, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\ProgramData\miniconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\main.py", line 43, in main
    await crawler.start()
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\core.py", line 66, in start
    await self.search()
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\core.py", line 95, in search
    posts_res = await self.dy_client.search_info_by_keyword(keyword=keyword,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\client.py", line 166, in search_info_by_keyword
    return await self.get("/aweme/v1/web/general/search/single/", query_params, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\client.py", line 101, in get
    await self.__process_req_params(params, headers)
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\client.py", line 80, in __process_req_params
    a_bogus = await get_a_bogus(query_string, post_data, headers["User-Agent"], self.playwright_page)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\help.py", line 37, in get_a_bogus
    return await get_a_bogus_from_playright(params, post_data, user_agent, page)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\help.py", line 48, in get_a_bogus_from_playright
    a_bogus = await page.evaluate(
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\venv\Lib\site-packages\playwright\async_api\_generated.py", line 8119, in evaluate
    await self._impl_obj.evaluate(
  File "C:\Users\DELL\Desktop\github\MediaCrawler\venv\Lib\site-packages\playwright\_impl\_page.py", line 416, in evaluate
    return await self._main_frame.evaluate(expression, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\venv\Lib\site-packages\playwright\_impl\_frame.py", line 278, in evaluate
    await self._channel.send(
  File "C:\Users\DELL\Desktop\github\MediaCrawler\venv\Lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\venv\Lib\site-packages\playwright\_impl\_connection.py", line 509, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\venv\Lib\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._errors.Error: TypeError: Cannot read properties of undefined (reading '2')
    at eval (eval at evaluate (:226:30), <anonymous>:1:49)
    at UtilityScript.evaluate (<anonymous>:233:19)
    at UtilityScript.<anonymous> (<anonymous>:1:44)

就在base_config里修改了PLATFORM、CRAWLER_MAX_NOTES_COUNT、ENABLE_GET_COMMENTS、ENABLE_GET_SUB_COMMENTS、DY_SPECIFIED_ID_LIS、DY_CREATOR_ID_LIST，不知道是什么错误，希望作者大大帮忙看下

**Comment by Windsland52** [comment]
好像是没加载出来，SAVE_LOGIN_STATE 改为 False就行了，不过刚开始爬又被屏蔽了。
2024-09-07 13:28:21 MediaCrawler ERROR (client.py:91) - request params incrr, response.text: 
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\client.py", line 92, in request
    raise Exception("account blocked")
Exception: account blocked
