### ISSUE TITLE
media_platform.douyin.exception.DataFetchError: account blocked

### ISSUE THREAD

**Issue by Windsland52** [NanmiCoder/MediaCrawler#432]
(venv) (base) C:\Users\DELL\Desktop\github\MediaCrawler>python main.py --platform dy --lt qrcode --type creator
2024-09-08 09:19:38 MediaCrawler INFO (login.py:105) - [DouYinLogin.login_by_qrcode] Begin login douyin by qrcode...
2024-09-08 09:19:47 MediaCrawler INFO (login.py:59) - [DouYinLogin.begin] login finished then check login state ...
2024-09-08 09:20:32 MediaCrawler INFO (login.py:68) - [DouYinLogin.begin] Login successful then wait for 5 seconds redirect ...
2024-09-08 09:20:37 MediaCrawler INFO (core.py:182) - [DouYinCrawler.get_creators_and_videos] Begin get douyin creators
2024-09-08 09:20:48 MediaCrawler INFO (__init__.py:125) - [store.douyin.save_creator] creator:{'user_id': 'MS4wLjABAAAAZJdMJWCk20BhmfjdkBtg_3OwU9tHA9aoKriwjS52wFo', 'nickname': '哈尔滨工业大学', 'gender': '未知', 'avatar': 'https://p3-pc.douyinpic.com/img/aweme-avatar/tos-cn-i-c9aec8xkvj_3b1457b8647644dfa81e4ddb2e7035c8~c5_300x300.jpeg?from=2956013662', 'desc': '在这里，你将看到不一样的哈工大', 'ip_location': 'IP属地： 
黑龙江', 'follows': 166, 'fans': 737274, 'interaction': 5704061, 'videos_count': 806, 'last_modify_ts': 1725758448610}
2024-09-08 09:20:58 MediaCrawler ERROR (client.py:91) - request params incrr, response.text: 
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\client.py", line 92, in request
    raise Exception("account blocked")
Exception: account blocked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\github\MediaCrawler\main.py", line 53, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\ProgramData\miniconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\main.py", line 43, in main
    await crawler.start()
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\core.py", line 72, in start
    await self.get_creators_and_videos()
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\core.py", line 189, in get_creators_and_videos
    all_video_list = await self.dy_client.get_all_user_aweme_posts(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\client.py", line 298, in get_all_user_aweme_posts
    aweme_post_res = await self.get_user_aweme_posts(sec_user_id, max_cursor)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\client.py", line 291, in get_user_aweme_posts
    return await self.get(uri, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\client.py", line 103, in get
    return await self.request(method="GET", url=f"{self._host}{uri}", params=params, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\client.py", line 95, in request
    raise DataFetchError(f"{e}, {response.text}")
media_platform.douyin.exception.DataFetchError: account blocked,

已经试过半天后重新登录，依旧会block

**Comment by Windsland52** [comment]
(venv) (base) C:\Users\DELL\Desktop\github\MediaCrawler>python main.py --platform dy --lt qrcode --type creator 
2024-09-08 09:59:32 MediaCrawler INFO (core.py:182) - [DouYinCrawler.get_creators_and_videos] Begin get douyin creators
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\github\MediaCrawler\main.py", line 53, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\ProgramData\miniconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\main.py", line 43, in main
    await crawler.start()
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\core.py", line 72, in start
    await self.get_creators_and_videos()
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\core.py", line 184, in get_creators_and_videos
    creator_info: Dict = await self.dy_client.get_user_info(user_id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\client.py", line 278, in get_user_info
    return await self.get(uri, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\client.py", line 101, in get
    await self.__process_req_params(params, headers)
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\client.py", line 80, in __process_req_params
    a_bogus = await get_a_bogus(query_string, post_data, headers["User-Agent"], self.playwright_page)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\help.py", line 37, in get_a_bogus
    return await get_a_bogus_from_playright(params, post_data, user_agent, page)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\help.py", line 49, in get_a_bogus_from_playright
    a_bogus = await page.evaluate(
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\venv\Lib\site-packages\playwright\async_api\_generated.py", line 8119, in evaluate
    await self._impl_obj.evaluate(
  File "C:\Users\DELL\Desktop\github\MediaCrawler\venv\Lib\site-packages\playwright\_impl\_page.py", line 416, in evaluate
    return await self._main_frame.evaluate(expression, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\venv\Lib\site-packages\playwright\_impl\_frame.py", line 278, in evaluate
    await self._channel.send(
  File "C:\Users\DELL\Desktop\github\MediaCrawler\venv\Lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\venv\Lib\site-packages\playwright\_impl\_connection.py", line 509, in wrap_api_call        
    return await cb()
           ^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\venv\Lib\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._errors.Error: TypeError: Cannot read properties of undefined (reading '2')
    at eval (eval at evaluate (:226:30), <anonymous>:1:49)
    at UtilityScript.evaluate (<anonymous>:233:19)
    at UtilityScript.<anonymous> (<anonymous>:1:44)

又一种报错，之前也有过，当时在media_platform/douyin/help.py加入await page.wait_for_timeout(20000)可以解决，现在又不行了

**Comment by Windsland52** [comment]
(venv) (base) C:\Users\DELL\Desktop\github\MediaCrawler>python main.py --platform dy --lt qrcode --type creator
2024-09-08 10:15:17 MediaCrawler INFO (core.py:182) - [DouYinCrawler.get_creators_and_videos] Begin get douyin creators
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\github\MediaCrawler\main.py", line 53, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\ProgramData\miniconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\main.py", line 43, in main
    await crawler.start()
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\core.py", line 72, in start
    await self.get_creators_and_videos()
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\core.py", line 184, in get_creators_and_videos
    creator_info: Dict = await self.dy_client.get_user_info(user_id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\client.py", line 278, in get_user_info
    return await self.get(uri, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\client.py", line 101, in get
    await self.__process_req_params(params, headers)
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\client.py", line 80, in __process_req_params
    a_bogus = await get_a_bogus(query_string, post_data, headers["User-Agent"], self.playwright_page)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\help.py", line 37, in get_a_bogus
    return await get_a_bogus_from_playright(params, post_data, user_agent, page)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\media_platform\douyin\help.py", line 49, in get_a_bogus_from_playright
    a_bogus = await page.evaluate(
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\venv\Lib\site-packages\playwright\async_api\_generated.py", line 8119, in evaluate
    await self._impl_obj.evaluate(
  File "C:\Users\DELL\Desktop\github\MediaCrawler\venv\Lib\site-packages\playwright\_impl\_page.py", line 416, in evaluate
    return await self._main_frame.evaluate(expression, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\venv\Lib\site-packages\playwright\_impl\_frame.py", line 278, in evaluate
    await self._channel.send(
  File "C:\Users\DELL\Desktop\github\MediaCrawler\venv\Lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\venv\Lib\site-packages\playwright\_impl\_connection.py", line 509, in wrap_api_call        
    return await cb()
           ^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\MediaCrawler\venv\Lib\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._errors.Error: TypeError: Cannot read properties of undefined (reading 'init')
    at eval (eval at evaluate (:226:30), <anonymous>:1:42)
    at UtilityScript.evaluate (<anonymous>:233:19)
    at UtilityScript.<anonymous> (<anonymous>:1:44)

改为无头会这样

**Comment by NanmiCoder** [comment]
经排查，使用playwright获取abogus参数的方式已失效，目前还没发现使用playwright获取的新方法。

https://github.com/NanmiCoder/MediaCrawler/blob/21e0d8f393119225adbe61cd26d2434ab2dc51e5/media_platform/douyin/help.py#L48-L51

如果着急的话可以看下[MediaCrawlerPro](https://github.com/MediaCrawlerPro)，因为它移除了playwright的依赖所有没有这个问题。

**Comment by Windsland52** [comment]
> 经排查，使用playwright获取abogus参数的方式已失效，目前还没发现使用playwright获取的新方法。
> 
> https://github.com/NanmiCoder/MediaCrawler/blob/21e0d8f393119225adbe61cd26d2434ab2dc51e5/media_platform/douyin/help.py#L48-L51
> 
> 如果着急的话可以看下[MediaCrawlerPro](https://github.com/MediaCrawlerPro)，因为它移除了playwright的依赖所有没有这个问题。

已经在alphaply/DouyinComments的基础上修改写了Windsland52/DouyinCommentsMonitor，没有用playwright

**Comment by NanmiCoder** [comment]
拉取新代码已支持
