### ISSUE TITLE
知乎内容爬取失败

### ISSUE THREAD

**Issue by seek4** [NanmiCoder/MediaCrawler#435]
![image](https://github.com/user-attachments/assets/4f47041e-54cd-4ea0-b61d-2fec99016173)
爬取知乎内容的时候报这个错。
执行的指令
`python main.py --platform zhihu --lt qrcode --type search`

报错
2024-09-11 17:34:33 MediaCrawler ERROR (client.py:77) - [ZhiHuClient.request] Requset Url: https://www.zhihu.com/api/v4/search_v3?gk_version=gz-gaokao&t=general&q=%E7%BC%96%E7%A8%8B%E5%89%AF%E4%B8%9A&correction=1&offset=0&limit=20&filter_fields=&lc_idx=0&show_all_topics=0&search_source=Filter&time_interval=&sort=&vertical=, Request error: {"error":{"message":"您当前请求存在异常，暂时限制本次访问","code":40362}}

2024-09-11 17:34:34 MediaCrawler ERROR (client.py:77) - [ZhiHuClient.request] Requset Url: https://www.zhihu.com/api/v4/search_v3?gk_version=gz-gaokao&t=general&q=%E7%BC%96%E7%A8%8B%E5%89%AF%E4%B8%9A&correction=1&offset=0&limit=20&filter_fields=&lc_idx=0&show_all_topics=0&search_source=Filter&time_interval=&sort=&vertical=, Request error: {"error":{"message":"您当前请求存在异常，暂时限制本次访问","code":40362}}

2024-09-11 17:34:35 MediaCrawler ERROR (client.py:77) - [ZhiHuClient.request] Requset Url: https://www.zhihu.com/api/v4/search_v3?gk_version=gz-gaokao&t=general&q=%E7%BC%96%E7%A8%8B%E5%89%AF%E4%B8%9A&correction=1&offset=0&limit=20&filter_fields=&lc_idx=0&show_all_topics=0&search_source=Filter&time_interval=&sort=&vertical=, Request error: {"error":{"message":"您当前请求存在异常，暂时限制本次访问","code":40362}}

Traceback (most recent call last):
  File "/Users/yangtong/mambaforge/envs/media_scrawler/lib/python3.9/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/Users/yangtong/pyworkspace/media_fork/MediaCrawler/media_platform/zhihu/client.py", line 79, in request
    raise ForbiddenError(response.text)
media_platform.zhihu.exception.ForbiddenError: {"error":{"message":"您当前请求存在异常，暂时限制本次访问","code":40362}}

**Comment by NanmiCoder** [comment]
待修复

**Comment by NanmiCoder** [comment]
已修复，你试试呢

**Comment by seek4** [comment]
赞，试了下可以了。

**Comment by NanmiCoder** [comment]
这个问题改动虽然小，但是真的排查了很长很长的时间。。。太恶心了🤢

**Comment by seek4** [comment]
知乎爬虫起家的，是比较恶心，盐选内容还限制了html读取
