### ISSUE TITLE
douyin爬取报错

### ISSUE THREAD

**Issue by Machoman6** [NanmiCoder/MediaCrawler#445]
Traceback (most recent call last):
  File "D:\crawler\MediaCrawler-main\main.py", line 55, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\zxnb\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\.venv\MediaCrawler-main\Lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
           ^^^^^^^^^^^^^^^^
  File "D:\pythonProject\.venv\MediaCrawler-main\Lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\.venv\MediaCrawler-main\Lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\.venv\MediaCrawler-main\Lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: 缺少 ')'

![image](https://github.com/user-attachments/assets/ceae3631-6751-4c08-a3b8-b137f86c5abf)

**Comment by NanmiCoder** [comment]
<img width="1628" alt="image" src="https://github.com/user-attachments/assets/74c74688-66b8-4201-8c36-61a28c4cf180">
