### ISSUE TITLE
全新拉取的项目，抖音返回request params incrr 直接退出了，a_bogus又更新拉？

### ISSUE THREAD

**Issue by kayzh324** [NanmiCoder/MediaCrawler#446]
'''
2024-09-30 16:23:26 MediaCrawler INFO (db.py:62) - [init_db] start init mediacrawler db connect object
2024-09-30 16:23:26 MediaCrawler INFO (db.py:64) - [init_db] end init mediacrawler db connect object
2024-09-30 16:23:26 MediaCrawler INFO (proxy_ip_pool.py:48) - [ProxyIpPool._is_valid_proxy] testing 218.93.206.242 is it valid 
2024-09-30 16:23:34 MediaCrawler INFO (login.py:105) - [DouYinLogin.login_by_qrcode] Begin login douyin by qrcode...

(eog:21073): Handy-WARNING **: 16:23:34.537: Using GtkSettings:gtk-application-prefer-dark-theme together with HdyStyleManager is unsupported. Please use HdyStyleManager:color-scheme instead.
2024-09-30 16:23:42 MediaCrawler INFO (login.py:59) - [DouYinLogin.begin] login finished then check login state ...
2024-09-30 16:24:12 MediaCrawler INFO (login.py:68) - [DouYinLogin.begin] Login successful then wait for 5 seconds redirect ...
2024-09-30 16:24:17 MediaCrawler INFO (core.py:179) - [DouYinCrawler.get_creators_and_videos] Begin get douyin creators
2024-09-30 16:24:17 MediaCrawler ERROR (client.py:93) - request params incrr, response.text: 
Traceback (most recent call last):
  File "/opt/MediaCrawler_limited/media_platform/douyin/client.py", line 94, in request
    raise Exception("account blocked")
Exception: account blocked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/MediaCrawler_limited/main.py", line 55, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/MediaCrawler_limited/main.py", line 45, in main
    await crawler.start()
  File "/opt/MediaCrawler_limited/media_platform/douyin/core.py", line 72, in start
    await self.get_creators_and_videos()
  File "/opt/MediaCrawler_limited/media_platform/douyin/core.py", line 181, in get_creators_and_videos
    creator_info: Dict = await self.dy_client.get_user_info(user_id)
  File "/opt/MediaCrawler_limited/media_platform/douyin/client.py", line 284, in get_user_info
    return await self.get(uri, params)
  File "/opt/MediaCrawler_limited/media_platform/douyin/client.py", line 105, in get
    return await self.request(method="GET", url=f"{self._host}{uri}", params=params, headers=headers)
  File "/opt/MediaCrawler_limited/media_platform/douyin/client.py", line 97, in request
    raise DataFetchError(f"{e}, {response.text}")
media_platform.douyin.exception.DataFetchError: account blocked,

**Comment by NanmiCoder** [comment]
可能出现验证码了，删除browser_data下对应平台目录 再重试下。

**Comment by kayzh324** [comment]
删掉browser_data，删掉虚拟环境重新装依赖，重新登录还是报错，随着错误，浏览器窗口自己关掉了。更奇怪的是，重新运行不再生成新的browser_data文件夹了，明明扫码登录和验证码流程都走完了。

**Comment by NanmiCoder** [comment]
我这边测试了 没问题。。。。不知道你那边出了什么问题
<img width="1852" alt="image" src="https://github.com/user-attachments/assets/118f4934-af6c-437a-94bd-84afc06bc57b">
