### ISSUE TITLE
weibo关键词爬取受限制求助！非常感谢您的代码！

### ISSUE THREAD

**Issue by Crackpot2002** [NanmiCoder/MediaCrawler#455]
大佬，您好！我用关键词爬取微博帖子的时候，爬到1000条左右就受限制无法再爬取了，请问这种有办法可以解决嘛？是否需要IP池或者多账号协同爬取？非常感谢大佬您的代码，爬取仅是为了完成课程作业，1000条不够用，不做别的用途。

**Comment by NanmiCoder** [comment]
微博好像是需要更换IP的，我一般没有爬取数据量的需求，所以还不知道爬取1000条就不行了，你试试加IP代理试试。

**Comment by Crackpot2002** [comment]
大佬，您好！感谢您的回复！我开启了更换IP，并重新配置了环境，报错如下。想请教这个是什么问题呀，我应该怎么解决呢？
Traceback (most recent call last):
  File "D:\爬虫\MediaCrawler-main\main.py", line 55, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "D:\爬虫\MediaCrawler-main\python310\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\爬虫\MediaCrawler-main\main.py", line 45, in main
    await crawler.start()
  File "D:\爬虫\MediaCrawler-main\media_platform\weibo\core.py", line 83, in start
    await self.search()
  File "D:\爬虫\MediaCrawler-main\media_platform\weibo\core.py", line 114, in search
    search_res = await self.wb_client.get_note_by_keyword(
  File "D:\爬虫\MediaCrawler-main\media_platform\weibo\client.py", line 117, in get_note_by_keyword
    return await self.get(uri, params)
  File "D:\爬虫\MediaCrawler-main\media_platform\weibo\client.py", line 69, in get
    return await self.request(method="GET", url=f"{self._host}{final_uri}", headers=headers, **kwargs)
  File "D:\爬虫\MediaCrawler-main\media_platform\weibo\client.py", line 45, in request
    response = await client.request(
  File "D:\爬虫\MediaCrawler-main\venv\lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\爬虫\MediaCrawler-main\venv\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "D:\爬虫\MediaCrawler-main\venv\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\爬虫\MediaCrawler-main\venv\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\爬虫\MediaCrawler-main\venv\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\爬虫\MediaCrawler-main\venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\爬虫\MediaCrawler-main\python310\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\爬虫\MediaCrawler-main\venv\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ProxyError: 454 Proxy Authentication Expired

**Comment by Crackpot2002** [comment]
好的，感谢大佬您的回复！想再请教一下什么时候可以修复呀？或者，Pro版本是否也有这个问题呢？虽然没有成功，但是再次感谢您的代码，让我学到了非常多东西！

**Comment by NanmiCoder** [comment]
Pro版本架构有区别，没有这个问题了。
