### ISSUE TITLE
xhs运行python main.py --platform xhs --lt cookie --type creator 报错。

### ISSUE THREAD

**Issue by jerry117** [NanmiCoder/MediaCrawler#457]
2024-10-21 14:20:46 MediaCrawler INFO (client.py:440) - [XiaoHongShuClient.get_all_notes_by_creator] got user_id:5b0c0d514eacab3fe9c6f688 notes len : 10
Traceback (most recent call last):
  File "/Users/jerryli/Workspace/MediaCrawler/.venv/lib/python3.12/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jerryli/Workspace/MediaCrawler/media_platform/xhs/client.py", line 504, in get_note_by_id_from_html
    note_dict = transform_json_keys(state)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jerryli/Workspace/MediaCrawler/media_platform/xhs/client.py", line 481, in transform_json_keys
    data_dict = json.loads(json_data)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jerryli/.pyenv/versions/3.12.1/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jerryli/.pyenv/versions/3.12.1/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jerryli/.pyenv/versions/3.12.1/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 53692 (char 53691)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jerryli/Workspace/MediaCrawler/main.py", line 66, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/Users/jerryli/.pyenv/versions/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/jerryli/Workspace/MediaCrawler/main.py", line 56, in main
    await crawler.start()
  File "/Users/jerryli/Workspace/MediaCrawler/media_platform/xhs/core.py", line 97, in start
    await self.get_creators_and_notes()
  File "/Users/jerryli/Workspace/MediaCrawler/media_platform/xhs/core.py", line 166, in get_creators_and_notes
    all_notes_list = await self.xhs_client.get_all_notes_by_creator(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jerryli/Workspace/MediaCrawler/media_platform/xhs/client.py", line 443, in get_all_notes_by_creator
    await callback(notes)
  File "/Users/jerryli/Workspace/MediaCrawler/media_platform/xhs/core.py", line 190, in fetch_creator_notes_detail
    note_details = await asyncio.gather(*task_list)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jerryli/Workspace/MediaCrawler/media_platform/xhs/core.py", line 228, in get_note_detail_async_task
    note_detail: Dict = await self.xhs_client.get_note_by_id_from_html(note_id, xsec_source, xsec_token)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jerryli/Workspace/MediaCrawler/.venv/lib/python3.12/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jerryli/Workspace/MediaCrawler/.venv/lib/python3.12/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jerryli/Workspace/MediaCrawler/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x12849f680 state=finished raised JSONDecodeError>]
mediacrawler-3.12➜  MediaCrawler git:(main) ✗

**Comment by NanmiCoder** [comment]
是否是最新的代码

**Comment by jerry117** [comment]
> 是否是最新的代码

拉的最新代码。这里也改了。
<img width="603" alt="image" src="https://github.com/user-attachments/assets/9751a749-3a5b-4c8d-8699-8164aaf96572">

**Comment by NanmiCoder** [comment]
换个其他账号+IP试试，排除下被控了

**Comment by jerry117** [comment]
好的感谢。

**Comment by learningpro** [comment]
我也遇到了类似的问题，打印了一下json_data内容发现有格式异常
<img width="473" alt="image" src="https://github.com/user-attachments/assets/8f008555-10b7-41a4-adf1-e5d3002838be">

**Comment by NanmiCoder** [comment]
https://github.com/NanmiCoder/MediaCrawler/pull/479
