### ISSUE TITLE
playwright报错 Cannot read properties of undefined (reading '2')：爬取dy数据，打开自动控制的chrome数秒后自动关闭报错。

### ISSUE THREAD

**Issue by Isaac-Jin** [NanmiCoder/MediaCrawler#500]
D:\Anaconda3\envs\crawler\python.exe D:/tmp/MediaCrawler/main.py --platform dy --lt qrcode --type detail
Traceback (most recent call last):
  File "D:\tmp\MediaCrawler\main.py", line 52, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "D:\Anaconda3\envs\crawler\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\tmp\MediaCrawler\main.py", line 43, in main
    await crawler.start()
  File "D:\tmp\MediaCrawler\media_platform\douyin\core.py", line 69, in start
    await self.get_specified_awemes()
  File "D:\tmp\MediaCrawler\media_platform\douyin\core.py", line 124, in get_specified_awemes
    aweme_details = await asyncio.gather(*task_list)
  File "D:\tmp\MediaCrawler\media_platform\douyin\core.py", line 134, in get_aweme_detail
    return await self.dy_client.get_video_by_id(aweme_id)
  File "D:\tmp\MediaCrawler\media_platform\douyin\client.py", line 176, in get_video_by_id
    res = await self.get("/aweme/v1/web/aweme/detail/", params, headers)
  File "D:\tmp\MediaCrawler\media_platform\douyin\client.py", line 101, in get
    await self.__process_req_params(params, headers)
  File "D:\tmp\MediaCrawler\media_platform\douyin\client.py", line 80, in __process_req_params
    a_bogus = await get_a_bogus(query_string, post_data, headers["User-Agent"], self.playwright_page)
  File "D:\tmp\MediaCrawler\media_platform\douyin\help.py", line 37, in get_a_bogus
    return await get_a_bogus_from_playright(params, post_data, user_agent, page)
  File "D:\tmp\MediaCrawler\media_platform\douyin\help.py", line 48, in get_a_bogus_from_playright
    a_bogus = await page.evaluate(
  File "D:\Anaconda3\envs\crawler\lib\site-packages\playwright\async_api\_generated.py", line 8495, in evaluate
    await self._impl_obj.evaluate(
  File "D:\Anaconda3\envs\crawler\lib\site-packages\playwright\_impl\_page.py", line 467, in evaluate
    return await self._main_frame.evaluate(expression, arg)
  File "D:\Anaconda3\envs\crawler\lib\site-packages\playwright\_impl\_frame.py", line 278, in evaluate
    await self._channel.send(
  File "D:\Anaconda3\envs\crawler\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "D:\Anaconda3\envs\crawler\lib\site-packages\playwright\_impl\_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
**playwright._impl._errors.Error: Page.evaluate: TypeError: Cannot read properties of undefined (reading '2')
    at eval (eval at evaluate (:234:30), <anonymous>:1:49)
    at UtilityScript.evaluate (<anonymous>:241:19)
    at UtilityScript.<anonymous> (<anonymous>:1:44)**

**Comment by NanmiCoder** [comment]
这个应该是之前的代码，请拉取最新代码之后尝试。
