### ISSUE TITLE
python main.py --help出现错误 求解答

### ISSUE THREAD

**Issue by SamWang8888** [NanmiCoder/MediaCrawler#523]
是啥原因呀。求解答555
PS Z:\MediaCrawler-main> python main.py --help
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    import cmd_arg
  File "Z:\MediaCrawler-main\cmd_arg\__init__.py", line 12, in <module>
    from .arg import *
  File "Z:\MediaCrawler-main\cmd_arg\arg.py", line 15, in <module>
    from tools.utils import str2bool
  File "Z:\MediaCrawler-main\tools\utils.py", line 15, in <module>
    from .crawler_util import *
  File "Z:\MediaCrawler-main\tools\crawler_util.py", line 26, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'
PS Z:\MediaCrawler-main>

**Comment by NanmiCoder** [comment]
https://github.com/NanmiCoder/MediaCrawler/issues/518
