### ISSUE TITLE
KeyError: 'items'

### ISSUE THREAD

**Issue by neohob** [NanmiCoder/MediaCrawler#57]
Traceback (most recent call last):
  File "/Users/xxx/Downloads/MediaCrawler/main.py", line 51, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/xxx/Downloads/MediaCrawler/main.py", line 45, in main
    await crawler.start()
  File "/Users/xxx/Downloads/MediaCrawler/media_platform/xhs/core.py", line 76, in start
    await self.search()
  File "/Users/xxx/Downloads/MediaCrawler/media_platform/xhs/core.py", line 101, in search
    note_details = await asyncio.gather(*task_list)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Downloads/MediaCrawler/media_platform/xhs/core.py", line 114, in get_note_detail
    return await self.xhs_client.get_note_by_id(note_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Downloads/MediaCrawler/media_platform/xhs/client.py", line 135, in get_note_by_id
    res_dict: Dict = res["items"][0]["note_card"]
                     ~~~^^^^^^^^^
KeyError: 'items'

**Comment by startzerokong** [comment]
挂代理请求的么

**Comment by neohob** [comment]
哈哈，是有一个🪜，去掉好像就好了，谢谢

**Comment by startzerokong** [comment]
> 哈哈，是有一个🪜，去掉好像就好了，谢谢

我是挂代理请求也遇见这个问题了 想看看你有没有挂代理的解决办法
