### ISSUE TITLE
大佬你好，我小红书登录成功，但是抓取时报错

### ISSUE THREAD

**Issue by stay-leave** [NanmiCoder/MediaCrawler#72]
```
PS D:\代码\MediaCrawler-main> python main.py --platform xhs --lt qrcode
2023-11-14  20:39:03 MediaCrawler INFO Begin create browser context ... 
2023-11-14  20:39:05 MediaCrawler INFO Begin create xiaohongshu API client ... 
2023-11-14  20:39:05 MediaCrawler INFO Begin to ping xhs... 
2023-11-14  20:39:06 MediaCrawler INFO Begin search xiaohongshu keywords 
2023-11-14  20:39:06 MediaCrawler INFO Current search keyword: python
2023-11-14  20:39:08 asyncio WARNING socket.send() raised exception. 
2023-11-14  20:39:08 asyncio WARNING socket.send() raised exception.
Traceback (most recent call last):
  File "D:\代码\MediaCrawler-main\main.py", line 51, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\代码\MediaCrawler-main\main.py", line 45, in main
    await crawler.start()
  File "D:\代码\MediaCrawler-main\media_platform\xhs\core.py", line 76, in start
    await self.search()
  File "D:\代码\MediaCrawler-main\media_platform\xhs\core.py", line 101, in search
    note_details = await asyncio.gather(*task_list)
  File "D:\代码\MediaCrawler-main\media_platform\xhs\core.py", line 114, in get_note_detail
    return await self.xhs_client.get_note_by_id(note_id)
  File "D:\代码\MediaCrawler-main\media_platform\xhs\client.py", line 135, in get_note_by_id
    res_dict: Dict = res["items"][0]["note_card"]
KeyError: 'items'
```
上面是我没开梯子的情况，下面是开了之后的情况：
```
File "C:\Users\22724\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError
```
求教这个怎么解决，顺便问下在哪设置搜索关键词，在下小白。感谢大佬

**Comment by stay-leave** [comment]
更新，刚刚又能爬了。但是帖子只爬了20条就又报错了
`2023-11-14  20:44:35 MediaCrawler INFO Begin get note id comments 647b2fb10000000011011a24
2023-11-14  20:44:35 asyncio WARNING socket.send() raised exception.
Traceback (most recent call last):
  File "D:\代码\MediaCrawler-main\main.py", line 51, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\代码\MediaCrawler-main\main.py", line 45, in main
    await crawler.start()
  File "D:\代码\MediaCrawler-main\media_platform\xhs\core.py", line 76, in start
    await self.search()
  File "D:\代码\MediaCrawler-main\media_platform\xhs\core.py", line 108, in search
    await self.batch_get_note_comments(note_id_list)
  File "D:\代码\MediaCrawler-main\media_platform\xhs\core.py", line 127, in batch_get_note_comments
    await asyncio.gather(*task_list)
  File "D:\代码\MediaCrawler-main\media_platform\xhs\core.py", line 133, in get_comments
    all_comments = await self.xhs_client.get_note_all_comments(note_id=note_id, crawl_interval=random.random())
  File "D:\代码\MediaCrawler-main\media_platform\xhs\client.py", line 189, in get_note_all_comments
    comments = comments_res["comments"]
KeyError: 'comments'`
请问这个怎么解决

**Comment by Tangsonghuai** [comment]
我来给你说吧
因为我都踩过一次坑了
1.就不说了
2。 配置超时 
`    async def request(self, method, url, **kwargs) -> Dict:
        async with httpx.AsyncClient(proxies=self.proxies) as client:
            response = await client.request(
                method, url, timeout=httpx.Timeout(30.0, connect=30.0, read=30.0),
                **kwargs
            )
        data: Dict = response.json()
        if data["success"]:
            return data.get("data", data.get("success", {}))
        elif data["code"] == self.IP_ERROR_CODE:
            raise IPBlockError(self.IP_ERROR_STR)
        else:
            raise DataFetchError(data.get("msg", None))`
            
        3. 是 评论为空的情况
        加判断即可

**Comment by stay-leave** [comment]
> 我来给你说吧 因为我都踩过一次坑了 1.就不说了 2。 配置超时 ` async def request(self, method, url, **kwargs) -> Dict: async with httpx.AsyncClient(proxies=self.proxies) as client: response = await client.request( method, url, timeout=httpx.Timeout(30.0, connect=30.0, read=30.0), **kwargs ) data: Dict = response.json() if data["success"]: return data.get("data", data.get("success", {})) elif data["code"] == self.IP_ERROR_CODE: raise IPBlockError(self.IP_ERROR_STR) else: raise DataFetchError(data.get("msg", None))`
> 
> ```
>     3. 是 评论为空的情况
>     加判断即可
> ```

谢谢大佬。现在可以简单的配置关键词和数量搜索笔记和评论了。我想自己定义抓取单个笔记的评论，这个大佬有思路吗？

**Comment by Tangsonghuai** [comment]
> > 我来给你说吧 因为我都踩过一次坑了 1.就不说了 2。 配置超时 ` async def request(self, method, url, **kwargs) -> Dict: async with httpx.AsyncClient(proxies=self.proxies) as client: response = await client.request( method, url, timeout=httpx.Timeout(30.0, connect=30.0, read=30.0), **kwargs ) data: Dict = response.json() if data["success"]: return data.get("data", data.get("success", {})) elif data["code"] == self.IP_ERROR_CODE: raise IPBlockError(self.IP_ERROR_STR) else: raise DataFetchError(data.get("msg", None))`
> > ```
> >     3. 是 评论为空的情况
> >     加判断即可
> > ```
> 
> 谢谢大佬。现在可以简单的配置关键词和数量搜索笔记和评论了。我想自己定义抓取单个笔记的评论，这个大佬有思路吗？

没有这样试过，不过
可以在batch list里声明某个笔记的id来单独输出，我这是瞎猜的

**Comment by stay-leave** [comment]
哈哈好，我再自己试试，谢谢大佬

**Comment by Tangsonghuai** [comment]
大兄弟，群主，周末加代码，就是加这一块的，到时候可以看看

**Comment by stay-leave** [comment]
好的，谢谢哥

**Comment by NanmiCoder** [comment]
拉下最新代码，已经修复这些问题了
