### ISSUE TITLE
MediaCrawler ERROR Ping xhs failed: TypeError: window._webmsxyw is not a function

### ISSUE THREAD

**Issue by linzhi0918** [NanmiCoder/MediaCrawler#86]
爬了几天都挺正常的没什么大问题，今天突然出现了之前没出现过的错误代码，请问怎么解决呀？谢谢！
尝试过删除browser_data底下的文件但是没有用。

```
/Users/MediaCrawler-main/main.py:54: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(main())
2023-11-30  15:37:10 MediaCrawler INFO Begin create browser context ... 
2023-11-30  15:37:12 MediaCrawler INFO Begin create xiaohongshu API client ... 
2023-11-30  15:37:12 MediaCrawler INFO Begin to ping xhs... 
2023-11-30  15:37:12 MediaCrawler ERROR Ping xhs failed: TypeError: window._webmsxyw is not a function
    at eval (eval at evaluate (:197:30), <anonymous>:1:25)
    at UtilityScript.evaluate (<anonymous>:204:19)
    at UtilityScript.<anonymous> (<anonymous>:1:44), and try to login again... 
2023-11-30  15:37:12 MediaCrawler INFO Begin login xiaohongshu ... 
2023-11-30  15:37:12 MediaCrawler INFO Begin login xiaohongshu by qrcode ... 
Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("xpath=//img[@class='qrcode-img']") to be visible
============================================================
2023-11-30  15:37:42 MediaCrawler INFO login failed , have not found qrcode please check .... 
Traceback (most recent call last):
  File "/Users/MediaCrawler-main/main.py", line 54, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/Applications/anaconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/MediaCrawler-main/main.py", line 48, in main
    await crawler.start()
  File "/Users/MediaCrawler-main/media_platform/xhs/core.py", line 74, in start
    await login_obj.begin()
  File "/Users/MediaCrawler-main/media_platform/xhs/login.py", line 49, in begin
    await self.login_by_qrcode()
  File "/Users/MediaCrawler-main/media_platform/xhs/login.py", line 140, in login_by_qrcode
    await login_button_ele.click()
  File "/Applications/anaconda3/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 15419, in click
    await self._impl_obj.click(
  File "/Applications/anaconda3/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 160, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "/Applications/anaconda3/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 489, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "/Applications/anaconda3/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/Applications/anaconda3/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 461, in wrap_api_call
    return await cb()
  File "/Applications/anaconda3/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("xpath=//*[@id='app']/div[1]/div[2]/div[1]/ul/div[1]/button")
============================================================
```

**Comment by NanmiCoder** [comment]
这是playwright在打开小红书首页时没有找到登录的按钮，所以超时了，把无头浏览器的选项设置为False，看下实际浏览器上提示了什么信息，看看是不是一些验证码之类的，修改位置：
https://github.com/NanmiCoder/MediaCrawler/blob/5affc8a6009faa3ed7593834972d3435bd4ae759/config/base_config.py#L15
