### ISSUE TITLE
请问大佬，这个项目的 python 是什么版本的啊

### ISSUE THREAD

**Issue by jiayifang** [NanmiCoder/MediaCrawler#90]
我mac 系统，python  3.8.2

报错
第二个错误
cannot import name 'OrderType' from 'media_platform.bilibili.field'

第一个错误
Traceback (most recent call last):
  File "/Users/zhangheng/Documents/project/git_python/MediaCrawler/main.py", line 8, in <module>
    from media_platform.bilibili import BilibiliCrawler
  File "/Users/zhangheng/Documents/project/git_python/MediaCrawler/media_platform/bilibili/__init__.py", line 6, in <module>
    from .core import *
  File "/Users/zhangheng/Documents/project/git_python/MediaCrawler/media_platform/bilibili/core.py", line 24, in <module>
    from .client import BilibiliClient
  File "/Users/zhangheng/Documents/project/git_python/MediaCrawler/media_platform/bilibili/client.py", line 20, in <module>
    class BilibiliClient:
  File "/Users/zhangheng/Documents/project/git_python/MediaCrawler/media_platform/bilibili/client.py", line 60, in BilibiliClient
    async def get_wbi_keys(self) -> tuple[str, str]:
TypeError: 'type' object is not subscriptable

**Comment by NanmiCoder** [comment]
这是一个 bug，已经修复，拉下最新代码试试

**Comment by Comfident** [comment]
赶上直播了，但是还是这个错误好像，拉的最新代码
PS C:\Users\ZZX\Downloads\MediaCrawler-main\MediaCrawler-main> python main.py --platform xhs --lt qrcode --type
search
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from media_platform.bilibili import BilibiliCrawler
  File "C:\Users\ZZX\Downloads\MediaCrawler-main\MediaCrawler-main\media_platform\bilibili\__init__.py", line 6,
 in <module>
    from .core import *
  File "C:\Users\ZZX\Downloads\MediaCrawler-main\MediaCrawler-main\media_platform\bilibili\core.py", line 24, in
 <module>
    from .client import BilibiliClient
  File "C:\Users\ZZX\Downloads\MediaCrawler-main\MediaCrawler-main\media_platform\bilibili\client.py", line 20,
in <module>
    class BilibiliClient:
  File "C:\Users\ZZX\Downloads\MediaCrawler-main\MediaCrawler-main\media_platform\bilibili\client.py", line 62,
in BilibiliClient
    async def get_wbi_keys(self) -> tuple[str, str]:
TypeError: 'type' object is not subscriptable
PS C:\Users\ZZX\Downloads\MediaCrawler-main\MediaCrawler-main>

**Comment by NanmiCoder** [comment]
我本地先复现这个问题

**Comment by Comfident** [comment]
非常感谢您！

**Comment by NanmiCoder** [comment]
已经修复了，低一点的 python版本类型注释好像不支持 tuple[str, str]方式，新的提交已经更换typing 包中的 Tuple 方式https://github.com/NanmiCoder/MediaCrawler/blob/f71d0864645e9bf1dd43cffcf6cf82bddf7d01f7/media_platform/bilibili/client.py#L62-L63

**Comment by Comfident** [comment]
thank you a lot, brilliant!
this issue can be closed!

**Comment by jiayifang** [comment]
bugfix
