### ISSUE TITLE
asyncio ERROR Task was destroyed but it is pending!

### ISSUE THREAD

**Issue by Comfident** [NanmiCoder/MediaCrawler#91]
<img width="954" alt="1" src="https://github.com/NanmiCoder/MediaCrawler/assets/105044766/6cf55fa5-5924-4bc3-a31f-a80227928383">
asyncio ERROR Task was destroyed but it is pending!

突然遇到这个问题，请问是什么原因🤝

**Comment by NanmiCoder** [comment]
之前是正常的吗？你直接使用 python 建立一个虚拟环境跑跑看，不要在 anaconda 中跑试试

**Comment by yaohongfenglove** [comment]
**I also encountered it today, after running for a few hours in a venv virtual environment.**

```
2023-12-11  13:02:52 MediaCrawler INFO Begin get note id 62a57777000000001d0127e5 comments 
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "D:\soft\path\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "main.py", line 56, in main
    await crawler.start()
  File "D:\data\program\galaxy\MediaCrawler\media_platform\xhs\core.py", line 110, in start
    await self.search()
  File "D:\data\program\galaxy\MediaCrawler\media_platform\xhs\core.py", line 158, in search
    await self.batch_get_note_comments(note_id_list, keyword=keyword)
  File "D:\data\program\galaxy\MediaCrawler\media_platform\xhs\core.py", line 192, in batch_get_note_comments
    await asyncio.gather(*task_list)
akeupMethWrapper object at 0x0000018E7F5CFE20>()]> cb=[gather.<locals>._done_callback() at D:\soft\path\Python38\lib\asyncio\tasks.py:769]>
2023-12-11  13:02:53 asyncio ERROR Task was destroyed but it is pending!
task: <Task pending name='6357c0d20000000015023907' coro=<XiaoHongShuCrawler.get_comments() running at D:\data\program\galaxy\MediaCrawler\media_platform\xhs\core.py:196> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0000018E7F5CFB80>()]> cb=[gather.<locals>._done_callback() at D:\soft\path\Python38\lib\asyncio\tasks.py:769]>
2023-12-11  13:02:53 asyncio ERROR Task was destroyed but it is pending!
task: <Task pending name='648adb390000000027003af0' coro=<XiaoHongShuCrawler.get_comments() running at D:\data\program\galaxy\MediaCrawler\media_platform\xhs\core.py:196> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0000018E7F5CF700>()]> cb=[gather.<locals>._done_callback() at D:\soft\path\Python38\lib\asyncio\tasks.py:769]>
2023-12-11  13:02:53 asyncio ERROR Task was destroyed but it is pending!
task: <Task pending name='62a57777000000001d0127e5' coro=<XiaoHongShuCrawler.get_comments() running at D:\data\program\galaxy\MediaCrawler\media_platform\xhs\core.py:198> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0000018E7F5CF5B0>()]> cb=[gather.<locals>._done_callback() at D:\soft\path\Python38\lib\asyncio\tasks.py:769, ProtocolCallback.__init__.<locals>.cb() at D:\data\program\galaxy\MediaCrawler\venv\lib\site-packages\playwright\_impl\_connection.py:185]>

```

**Comment by NanmiCoder** [comment]
本地复现之后修复

**Comment by Comfident** [comment]
sorry for late reply
this error may disappear when turn off and try again

**Comment by AllenZHU23** [comment]
I have also encountered this issue, and I found that it always emerge when I tried to get sub-comments data.
![issue_task pending](https://github.com/NanmiCoder/MediaCrawler/assets/150229263/0f7a3459-ba72-483b-9506-5a9bf9215816)
![issue_position](https://github.com/NanmiCoder/MediaCrawler/assets/150229263/20a56207-9c4d-4a0b-8e47-dd8f45e7797e)

**Comment by yaohongfenglove** [comment]
姚宏锋已收到您的来信，谢谢。

**Comment by AllenZHU23** [comment]
I have also encountered this issue, and I found that it always emerge when I tried to get sub-comments data.
![issue_task pending](https://github.com/NanmiCoder/MediaCrawler/assets/150229263/1707d13c-e5b2-4654-bd10-132447d1b4f0)
![issue_position](https://github.com/NanmiCoder/MediaCrawler/assets/150229263/6bb83ddb-9f27-4ee2-bb47-1a15e4801132)

**Comment by NanmiCoder** [comment]
The functionality to retrieve child comments is currently untested and may contain unexpected errors. There are plans to iteratively iterate the functionality of all child comments in the future.

**Comment by AllenZHU23** [comment]
@NanmiCoder Thank you for your prompt response~ 
And I found that getting the sub-comment basically works when the extra comma is removed here:
![image](https://github.com/NanmiCoder/MediaCrawler/assets/150229263/724d7cf5-2917-4093-861d-1ca618a5750b)
